import React from "react";

const FAQ = () => {
  return (
    <div className="faq">
      <div className="faq-container">
        <h1>FAQ</h1>
        <h2>What is DALL·E?</h2>
        <p>
          DALL·E is a text-to-image generative AI model developed by{" "}
          <a target={"_blank"} href={"https://openai.com/"}>
            OpenAI
          </a>
          . Simply write creative prompts for what you want to see and watch
          DALL·E generate them in seconds!
        </p>
        <h2>How do I improve the results of the DALL·E images?</h2>
        <p>
          The output generated by DALL·E is highly correlated to how you
          structure your prompts. Adding more descriptive detail to the prompt
          will push DALL·E to output more complex results. For example, a dog
          playing a trumpet standing on a rainbow in space.
        </p>
        <img src="../../static/dogTrumpet.png"></img>
        <h2>How long does shipping take?</h2>
        <p>Shipping will be 2-3 weeks after order placement.</p>
        <h2>Can I keep the digital 3D models and sell them as NFT's?</h2>
        <p>
          StyleGenie is currently working on NFT integration. Stay up to date at
          our twitter @StyleGenie
        </p>
      </div>
    </div>
  );
};

export default FAQ;
